---
  - name: Install needed packages for the development environment
    apt: pkg={{item}} state=installed
    with_items:
      - build-essential
      - libbluetooth-dev
      - bluez
      - rfkill
      - bluetooth
      - lib32z1
      - lib32ncurses5
      - unzip
      - minicom
      - screen
      - binutils-avr
      - binutils-arm-none-eabi

  - name: Create directories
    file: path={{item}} state=directory
    with_items:
      - "{{downloads}}"

  - name: See if cross-compiler installed
    stat: path=/usr/local/gcc-arm-none-eabi-4_9-2015q2
    register: cc_installed

  - name: See if cross-compiler copied
    stat: path="{{downloads}}/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2"
    register: cc_copied
    when: not cc_installed.stat.exists

  - name: Copy cross compiler
    copy: src=gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 dest={{downloads}}/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2
    when: not cc_installed.stat.exists and not cc_copied.stat.exists

  - name: Unarchive the cross compiler
    unarchive: src={{downloads}}/gcc-arm-none-eabi-4_9-2015q2-20150609-linux.tar.bz2 dest=/usr/local/ copy=no mode="u=rwx,g=rwx,o=rwx"
    when: not cc_installed.stat.exists

  - name: See if JLink is installed
    shell: "dpkg -l | grep jlink"
    ignore_errors: true
    register: jlink_installed

  - name: See if Jlink has already been copied
    stat: path={{downloads}}/jlink_5.2.4_x86_64.deb
    register: jlink_copied
    when: jlink_installed.rc == 1

  - name: Copy JLink
    copy: src=jlink_5.2.4_x86_64.deb dest={{downloads}}
    when: jlink_installed.rc == 1 and not jlink_copied.stat.exists

  - name: Install JLink
    shell: sudo dpkg -i {{downloads}}/jlink_5.2.4_x86_64.deb
    when: jlink_installed.rc == 1

  - name: Update fruitymesh-devenv project from git
    git: repo=https://github.com/mwaylabs/fruitymesh-devenv.git dest={{nrf}} accept_hostkey=true

  - name: See if Jlink symlink exists
    stat: path={{nrf}}/tools/jlink
    register: jlink_link

  - name: See if SDK was downloaded
    stat: path={{downloads}}/nRF51_SDK_9.0.0_2e23562.zip
    register: sdk_zip

  - name: Download the SDK
    get_url: url=https://developer.nordicsemi.com/nRF51_SDK/nRF51_SDK_v9.x.x/nRF51_SDK_9.0.0_2e23562.zip dest={{downloads}}
    when: not sdk_zip.stat.exists

  - name: See if SDK was installed
    stat: path={{nrf_sdk_9_0}}/components
    register: sdk_unzipped

  - name: Install the SDK
    unarchive: src={{downloads}}/nRF51_SDK_9.0.0_2e23562.zip dest={{nrf_sdk_9_0}} mode="u=rw,g=r,o=r" copy=no
    when: not sdk_unzipped.stat.exists

  - name: See if EHAL link exists
    stat: path={{nrf}}/sdk/ehal_2015_09_08/ARM/CMSIS
    register: ehal_link

  - name: Update fruitymesh project from git
    git: repo=https://github.com/mwaylabs/fruitymesh.git dest={{nrf}}/projects/fruitymesh accept_hostkey=true

  - name: Create nrf51 sdk latest symlink
    file: src={{nrf_sdk_9_0}} dest={{nrf}}/sdk/nrf51_sdk_latest state=link

  - name: Create ehal latest symlink
    file: src={{nrf}}/sdk/ehal_2015_09_08 dest={{nrf}}/sdk/ehal_latest state=link

  - name: Fix path to GNU
    lineinfile: dest={{nrf}}/sdk/nrf51_sdk_latest/components/toolchain/gcc/Makefile.posix regexp='^GNU_INSTALL_ROOT :=' line='GNU_INSTALL_ROOT := /usr/local/gcc-arm-none-eabi-4_9-2015q2'

  - name: Copy patched header file
    copy: src=nrf_svc.h dest={{nrf}}/sdk/nrf51_sdk_latest/components/softdevice/s130/headers/nrf_svc.h owner={{user}} group={{user}}

  - name: Create jlink symlink
    file: src=/usr/bin/JLinkExe dest={{nrf}}/tools/jlink state=link
    when: not jlink_link.stat.exists

  - name: Create EHAL symlink
    file: src={{nrf}}/sdk/arm_cmsis_4_3/CMSIS dest={{nrf}}/sdk/ehal_latest/ARM/CMSIS state=link
    when: not ehal_link.stat.exists

  - name: Set ownership
    file: path={{item}} owner={{user}} group={{user}} recurse=yes
    with_items:
      - "{{nrf}}"
      - "{{downloads}}"

  - name: Remove unnecessary files
    file: path={{item}} state=absent
    with_items:
      - '"{{nrf}}/sdk/nrf_sdk_9_0/put_sdk_9_0_0 files here"'
      - '"{{nrf}}/projects/put your project folders here"'
